feat：Add talk pages（#116）
OpenIMSDK/OpenKF pull request #153
Opened 2023-08-04 15:42 UTC by MC-kanon

<br>

#### 🔍 What type of PR is this?

#### 👀 What this PR does / why we need it:

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

#### 🅰 Which issue(s) this PR fixes:

Fixes #116

#### 📝 Special notes for your reviewer:

#### 🎯 Describe how to verify it

#### 📑 Additional documentation e.g., RFC, notion, Google docs, usage docs, etc.:

2023-08-05 04:14 UTC, IRONICBo commented
@MC-kanon Please sign your CLA and recheck, with `I have read the CLA Document and I hereby sign the CLA` comment.

2023-08-05 04:20 UTC, IRONICBo requested changes

2023-08-05 04:20 UTC, IRONICBo commented on web/src/views/chat/index.vue
> +    '1111111111111111111111111111111111111111111111111111111111111111111111111111111',
It's your mock data?

2023-08-05 04:20 UTC, IRONICBo commented on web/src/views/chat/index.vue
> +    console.log('发送了一条消息...');
Use english please.

2023-08-05 04:20 UTC, IRONICBo commented on web/src/components/Message.vue
> +        <t-avatar :image="avatarSrc" v-if="isLeft" size="large" />
avatarSrc maybe empty, so you can update with character avatar.
```bash
        <template #avatar="{ row }">
          <t-avatar v-if="row.avatar === ''">{{ getAvatarString(row.nickname) }}</t-avatar>
          <t-avatar v-else :alt="getAvatarString(row.nickname)" hide-on-load-failed="true" :image="row.avatar" />
        </template>
```

2023-08-05 07:15 UTC, MC-kanon commented on web/src/views/chat/index.vue
> +    '1111111111111111111111111111111111111111111111111111111111111111111111111111111',
temp data

2023-08-05 07:15 UTC, MC-kanon commented on web/src/views/chat/index.vue
> +    console.log('发送了一条消息...');
ok

2023-08-05 07:15 UTC, MC-kanon commented
I have read the CLA Document and I hereby sign the CLA

2023-08-05 07:23 UTC, MC-kanon commented
I have read the CLA Document and I hereby sign the CLA

2023-08-06 03:02 UTC, cubxxw approved these changes

2023-08-06 03:56 UTC, IRONICBo commented
/approve

2023-08-06 03:56 UTC, IRONICBo approved these changes

2023-08-06 04:07 UTC, merged